import { Text, SafeAreaView, Ionicons } from '../../src/localized-ui';

import { LinearGradient } from 'expo-linear-gradient';

import { router } from '../../src/navigation';
import { ScrollView, StyleSheet, View } from 'react-native';

import { PressScale } from '../../src/components';
import { colors,shadow,shadowStrong,space } from '../../src/theme';

export default function Communicate(){return <SafeAreaView style={s.safe} edges={['top']}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.content}>
  <Text style={s.eyebrow}>COMMUNICATE</Text><Text style={s.heading}>Choose what feels natural.</Text><Text style={s.intro}>Hum Ahang adapts the screen for both people.</Text>
  <PressScale label="Start face-to-face conversation" onPress={()=>router.push({pathname:'/conversation',params:{partner:'hearing',face:'1'}})} style={s.heroWrap}><LinearGradient colors={['#8063F7','#6848EA']} style={s.hero}><View style={s.orbit}/><View style={s.heroIcon}><Ionicons name="swap-vertical" size={28} color={colors.primary}/></View><Text style={s.heroKicker}>ONE PHONE · TWO PEOPLE</Text><Text style={s.heroTitle}>Face-to-face</Text><Text style={s.heroText}>The screen turns for each person automatically.</Text><View style={s.heroAction}><Text style={s.heroActionText}>Start now</Text><Ionicons name="arrow-forward" size={17} color={colors.surface}/></View></LinearGradient></PressScale>
  <Text style={s.section}>Other ways to connect</Text><View style={s.grid}>
    <Tool title="Live captions" detail="Speech becomes large text" icon="mic-outline" tint={colors.pastelBlue} color="#238EBB" onPress={()=>router.push('/transcription')}/>
    <Tool title="Quick Speak" detail="Play a saved phrase" icon="volume-high-outline" tint={colors.pastelYellow} color="#DA9227" onPress={()=>router.push('/quick-speak')}/>
  </View>
  <PressScale label="Open Sign Assistant Beta" onPress={()=>router.push('/sign-assistant')} style={s.beta}><View style={s.betaIcon}><Ionicons name="hand-left-outline" size={23} color="#D94F7A"/></View><View style={{flex:1}}><View style={s.betaTitleRow}><Text style={s.betaTitle}>Sign Assistant</Text><Text style={s.badge}>BETA</Text></View><Text style={s.betaText}>Simple hand gestures · experimental</Text></View><Ionicons name="chevron-forward" size={18} color="#9E9BA8"/></PressScale>
</ScrollView></SafeAreaView>}

function Tool({title,detail,icon,tint,color,onPress}:{title:string;detail:string;icon:any;tint:string;color:string;onPress():void}){return <PressScale label={title} onPress={onPress} style={s.tool}><View style={[s.toolIcon,{backgroundColor:tint}]}><Ionicons name={icon} size={25} color={color}/></View><Text style={s.toolTitle}>{title}</Text><Text style={s.toolText}>{detail}</Text><View style={s.toolArrow}><Ionicons name="arrow-forward" size={15} color={color}/></View></PressScale>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},content:{padding:space.lg,paddingBottom:34},eyebrow:{fontSize:10,fontWeight:'700',letterSpacing:1.4,color:colors.primary},heading:{fontSize:28,lineHeight:34,fontWeight:'700',letterSpacing:-.8,color:colors.ink,marginTop:5},intro:{fontSize:13,lineHeight:19,color:colors.muted,marginTop:4,marginBottom:18},heroWrap:{borderRadius:25,...shadowStrong},hero:{minHeight:235,borderRadius:25,padding:20,overflow:'hidden'},orbit:{position:'absolute',width:190,height:190,borderRadius:95,borderWidth:28,borderColor:'#FFFFFF0E',right:-45,top:-35},heroIcon:{width:54,height:54,borderRadius:18,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},heroKicker:{fontSize:9,fontWeight:'700',letterSpacing:.8,color:'#EDE8FF',marginTop:18},heroTitle:{fontSize:27,fontWeight:'700',color:colors.surface,marginTop:4},heroText:{fontSize:12,lineHeight:18,color:'#E5DEFF',marginTop:4},heroAction:{alignSelf:'flex-start',marginTop:16,minHeight:44,paddingHorizontal:15,borderRadius:15,backgroundColor:'#FFFFFF1F',flexDirection:'row',alignItems:'center',gap:8},heroActionText:{fontSize:12,fontWeight:'700',color:colors.surface},section:{fontSize:17,fontWeight:'700',color:colors.ink,marginTop:25,marginBottom:11},grid:{flexDirection:'row',gap:11},tool:{flex:1,minHeight:174,borderRadius:21,backgroundColor:colors.surface,padding:14,paddingBottom:50,...shadow},toolIcon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},toolTitle:{fontSize:15,fontWeight:'700',color:colors.ink,marginTop:15},toolText:{fontSize:11,lineHeight:16,color:colors.muted,marginTop:4},toolArrow:{position:'absolute',right:12,bottom:12,width:31,height:31,borderRadius:11,backgroundColor:colors.cream,alignItems:'center',justifyContent:'center'},beta:{minHeight:78,marginTop:12,borderRadius:20,backgroundColor:colors.surface,padding:12,flexDirection:'row',alignItems:'center',gap:11,...shadow},betaIcon:{width:48,height:48,borderRadius:16,backgroundColor:colors.pastelPink,alignItems:'center',justifyContent:'center'},betaTitleRow:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:7},betaTitle:{fontSize:14,fontWeight:'700',color:colors.ink},badge:{fontSize:8,fontWeight:'800',letterSpacing:.6,color:'#B63E65',backgroundColor:colors.pastelPink,paddingHorizontal:6,paddingVertical:3,borderRadius:6},betaText:{fontSize:11,color:colors.muted,marginTop:3}});
