const en = {
  title: 'Emergency contact QR', back: 'Go back',
  subtitle: 'Let someone call your trusted contact from their own phone.',
  entry: 'Emergency contact QR',
  privacy: 'Revealing this QR shows your saved contact’s name and number, even if hidden on your passport. Anyone scanning or photographing it can keep the number. Copies cannot expire or be revoked.',
  reveal: 'Reveal contact & QR', hide: 'Hide contact & QR',
  scan: 'Scan to call my emergency contact', contact: 'My trusted contact',
  instructions: 'Scan with the other phone. This QR contains the exact +country-code number, without a tel: prefix. Your scanner may offer Call or Copy. Check that the dialer matches the displayed number before calling.',
  boundary: 'This QR contains only the phone number—not your full passport. Creating or showing it does not place a call. No server or internet is needed to generate the QR; calling still needs a supported phone service.',
  fallback: 'If the scanner does not recognize the phone action, enter the displayed number manually.',
  missing: 'No valid trusted contact is saved. Add one through Profile → Settings → Passport details.',
  format: 'For this QR, save an international-format contact number beginning with + and the country code. For Pakistan, use +92 without the initial local 0. Update it in Passport details; we will not guess a country code.',
  settings: 'Open Passport settings', loading: 'Loading saved contact…',
  loadError: 'Your saved contact could not be loaded. Retry before creating a QR.', retry: 'Retry loading profile',
  generationError: 'The QR could not be created. Please try revealing it again.',
  qrLabel: 'Phone-number QR for the displayed emergency contact',
};
const ur: typeof en = {
  title: 'ہنگامی رابطے کا کیو آر', back: 'واپس جائیں',
  subtitle: 'دوسرے شخص کو اپنے فون سے آپ کے قابلِ اعتماد رابطے کو کال کرنے دیں۔',
  entry: 'ہنگامی رابطے کا کیو آر',
  privacy: 'یہ کیو آر دکھانے سے محفوظ رابطے کا نام اور نمبر ظاہر ہوگا، چاہے پاسپورٹ پر چھپا ہو۔ اسے اسکین کرنے یا تصویر لینے والا نمبر اپنے پاس رکھ سکتا ہے۔ پرانی کاپیوں کو ختم یا منسوخ نہیں کیا جا سکتا۔',
  reveal: 'رابطہ اور کیو آر دکھائیں', hide: 'رابطہ اور کیو آر چھپائیں',
  scan: 'میرے ہنگامی رابطے کو کال کرنے کے لیے اسکین کریں', contact: 'میرا قابلِ اعتماد رابطہ',
  instructions: 'دوسرے فون سے اسکین کریں۔ کیو آر میں صرف + اور ملک کے کوڈ سمیت اصل نمبر ہے؛ اس سے پہلے کوئی لفظ نہیں۔ اسکینر کال یا نقل کرنے کا اختیار دے سکتا ہے۔ کال سے پہلے ڈائلر کا نمبر دکھائے گئے نمبر سے ملائیں۔',
  boundary: 'کیو آر میں صرف فون نمبر ہے، پورا پاسپورٹ نہیں۔ اسے بنانے یا دکھانے سے کال نہیں ہوتی۔ کیو آر بنانے کے لیے سرور یا انٹرنیٹ ضروری نہیں؛ کال کے لیے دستیاب فون سروس چاہیے۔',
  fallback: 'اگر اسکینر کال کا اختیار نہ دکھائے تو نظر آنے والا نمبر خود درج کریں۔',
  missing: 'کوئی درست قابلِ اعتماد رابطہ محفوظ نہیں۔ پروفائل، سیٹنگز، پاسپورٹ کی تفصیلات میں رابطہ شامل کریں۔',
  format: 'اس کیو آر کے لیے نمبر + اور ملک کے کوڈ کے ساتھ محفوظ کریں۔ پاکستان کے لیے ابتدائی مقامی 0 ہٹا کر +92 استعمال کریں۔ پاسپورٹ کی تفصیلات میں درست کریں؛ ملک کا کوڈ خود فرض نہیں کیا جائے گا۔',
  settings: 'پاسپورٹ کی سیٹنگز کھولیں', loading: 'محفوظ رابطہ لوڈ ہو رہا ہے…',
  loadError: 'محفوظ رابطہ لوڈ نہیں ہو سکا۔ کیو آر بنانے سے پہلے دوبارہ کوشش کریں۔', retry: 'پروفائل دوبارہ لوڈ کریں',
  generationError: 'کیو آر نہیں بن سکا۔ اسے دوبارہ دکھانے کی کوشش کریں۔',
  qrLabel: 'دکھائے گئے ہنگامی رابطے کو کال کرنے کا کیو آر',
};
const roman: typeof en = {
  title: 'Hangami raabte ka QR', back: 'Wapas jayen', entry: 'Hangami raabte ka QR',
  subtitle: 'Doosra shakhs apne phone se aap ke bharosemand raabte ko call kar sake.',
  privacy: 'QR dikhane se mehfooz raabte ka naam aur number zahir hoga, chahe passport par chhupa ho. Scan ya tasveer lene wala number rakh sakta hai. Purani copies mansookh ya expire nahin ho saktin.',
  reveal: 'Raabta aur QR dikhayen', hide: 'Raabta aur QR chhupayen',
  scan: 'Mere hangami raabte ko call karne ke liye scan karein', contact: 'Mera bharosemand raabta',
  instructions: 'Doosre phone se scan karein. QR mein sirf + aur mulk ke code samait asal number hai, tel: prefix nahin. Scanner Call ya Copy de sakta hai. Call se pehle dialer ka number dikhaye gaye number se milayen.',
  boundary: 'QR mein sirf phone number hai, poora passport nahin. Ise banane ya dikhane se call nahin hoti. QR ke liye server ya internet nahin chahiye; call ke liye phone service chahiye.',
  fallback: 'Agar scanner call ka ikhtiyar na de to dikhaya gaya number khud darj karein.',
  missing: 'Koi durust bharosemand raabta mehfooz nahin. Profile, Tarteebat, Passport ki tafseelat mein raabta shamil karein.',
  format: 'Is QR ke liye + aur mulk ke code ke saath number mehfooz karein. Pakistan ke liye shuru ka maqami 0 hata kar +92 lagayen. Passport ki tafseelat mein durust karein; mulk ka code khud farz nahin kiya jayega.',
  settings: 'Passport ki tarteebat kholein', loading: 'Mehfooz raabta load ho raha hai…',
  loadError: 'Mehfooz raabta load nahin ho saka. QR banane se pehle dobara koshish karein.', retry: 'Profile dobara load karein',
  generationError: 'QR nahin ban saka. Ise dobara dikhane ki koshish karein.',
  qrLabel: 'Dikhaye gaye hangami raabte ke number ka QR',
};
export function getContactQrCopy(language: string) { return language === 'Roman Urdu' ? roman : language === 'اردو' || language === 'Urdu' ? ur : en; }
